### PR TITLE
Allow top-down configuration of target statuses

### LINKED ISSUE #19: Add switch for global vs local solvers (status codes)
As discussed in #17, we could add a switch to specify that the given solver is able to find a global optimum and decide infeasibility globally (e.g. BARON, KNITRO, SCIP) or will only give results that are valid locally (e.g. IPOPT).

### PR DESCRIPTION
**Pull request by rschwarz**
fixes #19

### CODE REVIEW

**Comment by rschwarz** [comment]
See https://github.com/SCIP-Interfaces/SCIP.jl/pull/130 for how this would simplify things for SCIP.jl (or other global solvers).

**Comment by rschwarz** [comment]
OK, I added both sets of `Dict`s, for local and global solvers. The `_LOCAL` variety is used by default, but I fear that this is still a breaking change. That is, solvers that are currently overriding the status codes in individual tests should now override the `Dict` instead.

**Comment by odow** [comment]
Breaking changes are fine. There are only a couple of packages using this.

**Comment by ccoffrin** [comment]
Agreed, breaking changes are fine. LGTM, @rschwarz ready for a merge and tag?

**Comment by rschwarz** [comment]
Yes, go ahead.

**Pull request merged**
