### PR TITLE
Model Updates for v0.2

### LINKED ISSUE #11: Ambiguous nlp-mi 003 test
One example:
https://github.com/lanl-ansi/MINLPTests.jl/blob/moi/src/nlp-mi/003_010.jl#L21

According to the constraint on y:
`@NLconstraint(m, y >= exp(x-2) - 2)`
where `x=3` is defined by maximizing the various functions.
`y` can also be `1` and not only `2` as the test suggests.

This could be changed to `@NLconstraint(m, y >= exp(x-2) - 1)` instead

### LINKED ISSUE #12: Revise Some MINLP Tests
The following `nlp-mi` tests should be revised, `003_010`,`003_011`,`003_012`,`003_016`.  The solutions changed when minor issues were fixed in Juniper.

### PR DESCRIPTION
**Pull request by ccoffrin**
Proposed model revisions for next release.

I believe this addresses the issues raised of @mlubin (re global solvers) and @Wikunia (re multiple optimal solutions).  If I missed anything please speak up.

CC @odow @frapac @leethargo

Closes #11, Closes #12 

Merge waiting on: https://github.com/JuliaLang/METADATA.jl/pull/22054

### CODE REVIEW

**Comment by frapac** [comment]
I have encountered also an issue running Knitro on `003_014` and `003_015` (see [this test](https://github.com/JuliaOpt/KNITRO.jl/blob/master/test/minlptests.jl#L25-#L26)). I was able to fix the problem by bounding the variables `x` and `y`, as you did. The other fixes look good to me!

**Comment by odow** [comment]
AmplNLWriter struggles with this one:
https://github.com/JuliaOpt/AmplNLWriter.jl/blob/0aaad316c7b99907f619b4b00337d87ab4a0facf/test/MINLPTests/run_minlptests.jl#L29
I think it needs a different starting point our bounds on the variables.

**Comment by ccoffrin** [comment]
Given that `log(x)` is problematic as `x` goes to 0 providing some positive lower bounds on x and y on seems reasonable.  Is there any chance the cause of the convergence issue is a bug in the NL file?

**Comment by ccoffrin** [comment]
@odow, would you like to double check that this revised `109_010` case will work for the AmplNLWriter?

**Comment by leethargo** [comment]
I understand that this branch is for JuMP up to `v0.18` (but not `v0.19`). I'm not going to test with SCIP.jl, then, since there was a complete rewrite for MOI.

**Comment by ccoffrin** [comment]
Sounds good @leethargo.  v0.3 will be moi compatible, I'll ping you once we have a PR for that version.

**Comment by odow** [comment]
@ccoffrin

Ipopt still fails to converge, but, Knitro converges in 10 iterations.

Here is the annotated NL file.  I think it is correct. Maybe this is an Ipopt bug?
```
# max  log(x)
# s.t. (y - 2)^2 + x <= 2
g3 1 1 0        # good
 2 1 1 0 0 0    # 2 vars, 1 constraint, 1 obj
 1 1            # 1 nl con, 1 nl obj
 0 0            # 0 networks
 1 1 0          # 1 var in nl, 1 var in obj
 0 0 0 1        # flag for output
 0 0 0 0 0      # no discrete variables
 2 1            # 2 nonzero jacobian, 1 gradient
 0 0            # 0 max name length
 0 0 0 0 0      # 0 common exprs
C0      # Constraints pow(-(y, 2), 2)
o5      # pow
o1      # -
v1      # y
n2      # 2
n2      # 2
O0 1    # Objective - maximize
o43     # log
v0      # x
d1      # Dual guess
0 0     # Constraint 0 - 0
x2      # Variable primal
0 0.1   # x₀ = 0.1
1 0.1   # y₀ = 0.1
r       # Constraint bounds
1 2.0   # C0 <= 2
b       # bounds
2 1.0   # x >= 1
2 1.0   # y >= 1
k1      # Jacobian column counts for 2 variables
1       # x is the only term
J0 2    # Jacobian 1st constraint, two terms
0 1.0   # variable 0, coef 1
1 0.0   # variable 1, coef 0 (false positive)
G0 1    # Gradient sparsity
0 0.0   # variable 0, coef 0 (false positive)
```

**Comment by ccoffrin** [comment]
@odow ok this still seems to be a mystery, but this NL example is helpful.

Now that v0.1 is tagged, I'll merge this and proceed with preparing v0.2

**Pull request merged**
